# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-05 06:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20180905_1346'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='confirmstring',
            options={'ordering': ['-c_time'], 'verbose_name': 'Validation code', 'verbose_name_plural': 'Validation codes'},
        ),
    ]
